front_controllers:
    resource: ../src/Controller/Front
    type: attribute
    name_prefix: front_

back_controllers:
    resource: ../src/Controller/Back
    type: attribute
    prefix: /admin/
    name_prefix: back_

root_controllers:
    resource: ../src/Controller
    type: attribute